version: "3.8"
services:

  fhir-forwarder:
    build:
      context: ./fhir-forwarder
    env_file: ./fhir-forwarder/.env
    ports:
      - "8003:8003"
    restart: unless-stopped
    networks:
      - lacpass-himnet

networks:
  lacpass-himnet:
    external: true
